Script started on 2023-02-13 19:47:24-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="197" LINES="33"]
]0;ajm94@gold17: ~/Desktop/CS 214/Labs/05[01;32majm94@gold17[00m:[01;34m~/Desktop/CS 214/Labs/05[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (defn sumSquares * [K[K[sequence][C[C[C[C[C[C[C[C[C[C (reduce * [K[K(fn[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Knums][C[C[C[C[C[C (reduce + (map #(* % %)[C[C[C[C[C[C[C nums)[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C)[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C)[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K(defn sumSquares [nums] (reduce + (map #(* % %) nums)))
[K#'user/sumSquares
user=> [Kuser=> [Kuser=> (sumSquares '(1 2 3)[C[C[C[C[C[C[C) [C[C[C[C[C[C[C[K(sumSquares '(1 2 3)) 
14
user=> [Kuser=> [Kuser=> (sumSquares '(1 2 3 4 5)[C[C[C[C[C[C[C[C[C[C[C)[C[C[C[C[C[C[C[K(sumSquares '(1 2 3 4 5))
55
user=> [Kuser=> [Kuser=> (sumSquares [-1 -2 -3 0 1][C[C[C[C[C[C[C[C[C[C[C[C[C[C)[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K(sumSquares [-1 -2 -3 0 1])
15
user=> [Kuser=> [Kuser=> 
[K]0;ajm94@gold17: ~/Desktop/CS 214/Labs/05[01;32majm94@gold17[00m:[01;34m~/Desktop/CS 214/Labs/05[00m$ exit

Script done on 2023-02-13 19:54:17-05:00 [COMMAND_EXIT_CODE="0"]
