Script started on 2023-01-19 20:02:39-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="197" LINES="12"]
]0;ajm94@gold21: ~/Desktop/CS 214/Labs/02[01;32majm94@gold21[00m:[01;34m~/Desktop/CS 214/Labs/02[00m$ bison -d example6.y[1Pflex example6.lex bison -d example6.y[Kcat example6.script observations.txt > lab02-results 
]0;ajm94@gold21: ~/Desktop/CS 214/Labs/02[01;32majm94@gold21[00m:[01;34m~/Desktop/CS 214/Labs/02[00m$ make
make: 'example6' is up to date.
]0;ajm94@gold21: ~/Desktop/CS 214/Labs/02[01;32majm94@gold21[00m:[01;34m~/Desktop/CS 214/Labs/02[00m$ ./example6
set humid 2
	Humidity set to 2
^[[A^[[B        set humid 0
	Humidity set to 0
]0;ajm94@gold21: ~/Desktop/CS 214/Labs/02[01;32majm94@gold21[00m:[01;34m~/Desktop/CS 214/Labs/02[00m$ exit

Script done on 2023-01-19 20:03:52-05:00 [COMMAND_EXIT_CODE="0"]
